server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 675347198FAKR
    url: jdbc:postgresql://localhost:5432/cinema
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true

  security:
    user:
      name: admin
      password: admin

  data:
    redis:
      databases:
        0:
          host: localhost
          port: 6379
        1:
          host: localhost
          port: 6379