server:
  port: 8080

spring:
  data:
    redis:
      databases:
        0:
          host: localhost
          port: 6379
        1:
          host: localhost
          port: 6379


  application:
    name: RestServerApplication
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db.changelog/db.master.yaml

  security:
    user:
      name: admin
      password: admin
