version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cinema
      - SPRING_DATA_REDIS_DATABASES_0_HOST=cache
      - SPRING_DATA_REDIS_DATABASES_0_PORT=6379
      - SPRING_DATA_REDIS_DATABASES_1_HOST=cache
      - SPRING_DATA_REDIS_DATABASES_1_PORT=6379

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cinema
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  db_data:
