version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/cinema
      - REDIS_URL_SCHEMA0=redis://cache:6379/0
      - REDIS_URL_SCHEMA1=redis://cache:6379/1

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cinema
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  db_data:
